apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idm-test

resources:
  - ../../base

images:
  - name: localhost:5001/idm-app
    newName: localhost:5001/idm-app
    newTag: 8c439a24bbbbba156649c103eab6f31033785b07

replicas:
  - name: idm-app
    count: 1

patches:
  - target:
      kind: Deployment
      name: idm-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: local-test
  - target:
      kind: Ingress
      name: idm-app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: idm-test.localhost
